### ISSUE TITLE
Upload failed

### ISSUE THREAD

**Issue by endangurura** [SanaMobile/sana.mds#2]
I just finished setting up the mds, openmrs and sana. I followed the instructions in the INSTALL file but I can't get the sana android client to upload procedures, its saying upload failed all the time. I tried to check the tomcat and mds logs but I can't figure out how to fix this. Can somebody help me fix this.
Thanks.

**Comment by endangurura** [comment]
.../mds/log
{
        "uuid": "28a70030-bfe7-47da-abe1-ed9e332d6575", 
        "level": 16, 
        "created": "2015-10-29T11:48:43", 
        "messages": "[{\"line_number\": 93, \"level_number\": 20, \"delta\": \"0.000s\", \"timestamp\": 1446137323.69, \"level_name\": \"INFO\", \"function_name\": \"create\", \"message\": \"Received saved procedure submission.\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}, {\"line_number\": 96, \"level_number\": 10, \"delta\": \"0.001s\", \"timestamp\": 1446137323.69, \"level_name\": \"DEBUG\", \"function_name\": \"create\", \"message\": \"Data: {'username': u'remote', 'procedure_guid': u'0', 'responses': u'{\\"1\\":{\\"answer\\":\\"Head and Neck\\",\\"type\\":\\"SELECT\\",\\"concept\\":\\"SURGERY SITE\\",\\"question\\":\\"Site of surgery\\"},\\"patientPhoto\\":{\\"answer\\":\\"\\",\\"type\\":\\"PICTURE\\",\\"concept\\":\\"PATIENT PHOTO\\",\\"question\\":\\"Take a picture of the patient.\\"},\\"patientEnrolled\\":{\\"answer\\":\\"Yes\\",\\"type\\":\\"RADIO\\",\\"id\\":\\"patientEnrolled\\",\\"question\\":\\"Does the patient already have an ID card?\\"},\\"5\\":{\\"answer\\":\\"\\",\\"type\\":\\"RADIO\\",\\"concept\\":\\"PAIN LEVEL\\",\\"question\\":\\"How bad is the pain?\\"},\\"11\\":{\\"answer\\":\\"No severe\\",\\"type\\":\\"ENTRY\\",\\"concept\\":\\"COMMENTS\\",\\"question\\":\\"Other comments:\\"},\\"9\\":{\\"answer\\":\\"\\",\\"type\\":\\"ENTRY\\",\\"concept\\":\\"FOLLOW UP PERIOD\\",\\"question\\":\\"Other duration:\\"},\\"patientBirthdateDay\\":{\\"answer\\":\\"01\\",\\"type\\":\\"SELECT\\",\\"concept\\":\\"BIRTHDATE DAY\\",\\"question\\":\\"Day:\\"},\\"2\\":{\\"answer\\":\\"Stomach\\",\\"type\\":\\"SELECT\\",\\"concept\\":\\"ORGAN\\",\\"question\\":\\"Organ\\"},\\"patientId\\":{\\"answer\\":\\"635872\\",\\"type\\":\\"PATIENT_ID\\",\\"concept\\":\\"PATIENT ID\\",\\"question\\":\\"Enter Patient\\'s Medical Record ID Number:\\"},\\"13\\":{\\"answer\\":\\"\\",\\"type\\":\\"PICTURE\\",\\"concept\\":\\"SURGERY SITE IMAGE\\",\\"question\\":\\"Take Picture of Surgery Site\\"},\\"8\\":{\\"answer\\":\\"3 days\\",\\"type\\":\\"SELECT\\",\\"concept\\":\\"FOLLOW UP PERIOD\\",\\"question\\":\\"Follow-up in:\\"},\\"patientLastName\\":{\\"answer\\":\\"Ho\\",\\"type\\":\\"ENTRY\\",\\"concept\\":\\"LAST NAME\\",\\"question\\":\\"Enter Patient\\'s Last Name:\\"},\\"6\\":{\\"answer\\":\\"No evidence of infection\\",\\"type\\":\\"RADIO\\",\\"concept\\":\\"INITIAL DIAGNOSIS\\",\\"question\\":\\"Diagnosis\\"},\\"12\\":{\\"answer\\":\\"Coordinates not acquired.\\",\\"type\\":\\"GPS\\",\\"concept\\":\\"GPS\\",\\"question\\":\\"Record Your Position\\"},\\"patientBirthdateYear\\":{\\"answer\\":\\"1993\\",\\"type\\":\\"ENTRY\\",\\"concept\\":\\"BIRTHDATE YEAR\\",\\"question\\":\\"Year:\\"},\\"7\\":{\\"answer\\":\\"Refer to University Hospital\\",\\"type\\":\\"MULTI_SELECT\\",\\"concept\\":\\"RECOMMENDATION\\",\\"question\\":\\"Recommendation\\"},\\"4\\":{\\"answer\\":\\"\\",\\"type\\":\\"RADIO\\",\\"concept\\":\\"WOUND DRAINAGE\\",\\"question\\":\\"Is the wound drainage:\\"},\\"3\\":{\\"answer\\":\\"\\",\\"type\\":\\"MULTI_SELECT\\",\\"concept\\":\\"SYMPTOMS\\",\\"question\\":\\"Check all that apply:\\"},\\"patientGender\\":{\\"answer\\":\\"Male\\",\\"type\\":\\"RADIO\\",\\"concept\\":\\"GENDER\\",\\"question\\":\\"Select Patient\\'s Gender:\\"},\\"patientBirthdateMonth\\":{\\"answer\\":\\"January\\",\\"type\\":\\"SELECT\\",\\"concept\\":\\"BIRTHDATE MONTH\\",\\"question\\":\\"Enter Patient\\'s Birthdate Month:\\"},\\"patientFirstName\\":{\\"answer\\":\\"Hi\\",\\"type\\":\\"ENTRY\\",\\"concept\\":\\"FIRST NAME\\",\\"question\\":\\"Enter Patient\\'s First Name:\\"},\\"procedureTitle\\":{\\"answer\\":\\"Surgery Follow-Up\\",\\"type\\":\\"HIDDEN\\",\\"id\\":\\"procedureTitle\\"}}', 'phone': u'5555555555', 'password': u'remoteUsR1', 'savedproc_guid': u'SPAJLBtEhqBueSUdlegPTR'}\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}, {\"line_number\": 79, \"level_number\": 10, \"delta\": \"0.004s\", \"timestamp\": 1446137323.69, \"level_name\": \"DEBUG\", \"function_name\": \"execute\", \"message\": \"(0.000) SELECT `core_procedure`.`id`, `core_procedure`.`uuid`, `core_procedure`.`created`, `core_procedure`.`modified`, `core_procedure`.`title`, `core_procedure`.`author`, `core_procedure`.`description`, `core_procedure`.`version`, `core_procedure`.`src`, `core_procedure`.`voided` FROM `core_procedure` WHERE `core_procedure`.`title` = '0' ; args=(u'0',)\", \"module\": \"util\", \"filename\": \"util.py\"}, {\"line_number\": 147, \"level_number\": 40, \"delta\": \"0.005s\", \"timestamp\": 1446137323.69, \"level_name\": \"ERROR\", \"function_name\": \"create\", \"message\": \"  File \\"\/opt\/sana\/sana.mds\/mds\/mrs\/handlers.py\\", line 101, in create\n    encounter, data, created = spform_to_encounter(form.cleaned_data)\n\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}, {\"line_number\": 147, \"level_number\": 40, \"delta\": \"0.005s\", \"timestamp\": 1446137323.69, \"level_name\": \"ERROR\", \"function_name\": \"create\", \"message\": \"  File \\"\/opt\/sana\/sana.mds\/mds\/api\/v1\/v2compatlib.py\\", line 323, in spform_to_encounter\n    procedure = get_v2(v2.Procedure,procedure_guid,\\"title\\")\n\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}, {\"line_number\": 147, \"level_number\": 40, \"delta\": \"0.005s\", \"timestamp\": 1446137323.69, \"level_name\": \"ERROR\", \"function_name\": \"create\", \"message\": \"  File \\"\/opt\/sana\/sana.mds\/mds\/api\/v1\/v2compatlib.py\\", line 295, in get_v2\n    obj = klazz.objects.get(*_{ field : v })\n\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}, {\"line_number\": 147, \"level_number\": 40, \"delta\": \"0.005s\", \"timestamp\": 1446137323.69, \"level_name\": \"ERROR\", \"function_name\": \"create\", \"message\": \"  File \\"\/usr\/lib\/python2.7\/dist-packages\/django\/db\/models\/manager.py\\", line 151, in get\n    return self.get_queryset().get(_args, **kwargs)\n\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}, {\"line_number\": 147, \"level_number\": 40, \"delta\": \"0.005s\", \"timestamp\": 1446137323.69, \"level_name\": \"ERROR\", \"function_name\": \"create\", \"message\": \"  File \\"\/usr\/lib\/python2.7\/dist-packages\/django\/db\/models\/query.py\\", line 307, in get\n    self.model._meta.object_name)\n\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}]",

**Comment by ewinkler** [comment]
Thanks for updating with the logging output. That helps significantly. It looks like the client is sending an erroneous value for the procedure being used, _procedure_guid': u'0'_.  It should actually be sending the uuid or title. This might be a bug but which client version are you using-e.g. build from the current source on Github or other?

**Comment by endangurura** [comment]
I tried different clients, First I tried the one from http://sana.mit.edu/mobile/download/. I tried also the ones from https://code.google.com/p/moca/downloads/list:  sana-release-1.1.1.apk,  sana-release-1.1.2.apk ... all of them didn't work. Now I'm trying to compile from source.

**Comment by ewinkler** [comment]
The sana-current.apk at the link you initially used needed to be updated. Should be corrected now. When building the client, the source available in the Github [sana.mobile repo](https://github.com/SanaMobile/sana.mobile) is what you will want to use. Clients built from the Googlecode repo definitely won't work.

**Comment by ewinkler** [comment]
Quick follow up comment. We are moving the documentation. The latest versions, as well as any updates, will now be available at http://dev.sanamobile.org/.

**Comment by endangurura** [comment]
I buillt a client from sana.mobile repo, but I'm still getting the upload failed errorr!

android logs:

Received from MDS:{
    "status": "FAILURE",
    "message": "Exception : <class 'mds.core.models.procedure.DoesNotExist'> Procedure matching query does not exist.   File \"/opt/sana/sana.mds/mds/mrs/handlers.py\", line 101, in create\n    encounter, data, created = spform_to_encounter(form.cleaned_data)\n",
    "code": 404,
    "errors": []
    }
10-30 09:43:01.721  29460-31066/org.sana.android D/MDSInterface2﹕ postResponses(...): org.sana.net.MDSResult@238db50b
10-30 09:43:01.721  29460-31066/org.sana.android D/MDSInterface2﹕ mds url: https://insightx.xyz//mds/
10-30 09:43:04.756  29460-31066/org.sana.android D/MDSInterface2﹕ doExecute() got response code 200
10-30 09:43:04.756  29460-31066/org.sana.android I/System.out﹕ dispatcher calls detatch()
10-30 09:43:04.761  29460-31066/org.sana.android D/MDSInterface2﹕ doExecute() Received from MDS:{
    "status": "FAILURE",
    "message": "Exception : <class 'mds.core.models.procedure.DoesNotExist'> Procedure matching query does not exist.   File \"/opt/sana/sana.mds/mds/mrs/handlers.py\", line 101, in create\n    encounter, data, created = spform_to_encounter(form.cleaned_data)\n",
    "code": 404,
    "errors": []
    }

**Comment by endangurura** [comment]
//mds/log
{
        "uuid": "fe07c76f-1789-4628-851a-7129a0ed73ed", 
        "level": 16, 
        "created": "2015-10-30T03:07:08", 
        "messages": "[{\"line_number\": 93, \"level_number\": 20, \"delta\": \"0.000s\", \"timestamp\": 1446192428.01, \"level_name\": \"INFO\", \"function_name\": \"create\", \"message\": \"Received saved procedure submission.\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}, {\"line_number\": 96, \"level_number\": 10, \"delta\": \"0.000s\", \"timestamp\": 1446192428.01, \"level_name\": \"DEBUG\", \"function_name\": \"create\", \"message\": \"Data: {'username': u'johndoe', 'procedure_guid': u'API Test', 'responses': u'{}', 'phone': u'9999999999', 'password': u'john123D', 'savedproc_guid': u'14d27ee3-1676-408d-a4c2-c6cedc0dd1af', 'subject': u'7ac6f734-be5a-4b2c-b211-ff523a87bc02'}\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}, {\"line_number\": 79, \"level_number\": 10, \"delta\": \"0.007s\", \"timestamp\": 1446192428.01, \"level_name\": \"DEBUG\", \"function_name\": \"execute\", \"message\": \"(0.000) SELECT `core_procedure`.`id`, `core_procedure`.`uuid`, `core_procedure`.`created`, `core_procedure`.`modified`, `core_procedure`.`title`, `core_procedure`.`author`, `core_procedure`.`description`, `core_procedure`.`version`, `core_procedure`.`src`, `core_procedure`.`voided` FROM `core_procedure` WHERE `core_procedure`.`title` = 'API Test' ; args=(u'API Test',)\", \"module\": \"util\", \"filename\": \"util.py\"}, {\"line_number\": 147, \"level_number\": 40, \"delta\": \"0.007s\", \"timestamp\": 1446192428.01, \"level_name\": \"ERROR\", \"function_name\": \"create\", \"message\": \"  File \\"\/opt\/sana\/sana.mds\/mds\/mrs\/handlers.py\\", line 101, in create\n    encounter, data, created = spform_to_encounter(form.cleaned_data)\n\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}, {\"line_number\": 147, \"level_number\": 40, \"delta\": \"0.007s\", \"timestamp\": 1446192428.01, \"level_name\": \"ERROR\", \"function_name\": \"create\", \"message\": \"  File \\"\/opt\/sana\/sana.mds\/mds\/api\/v1\/v2compatlib.py\\", line 323, in spform_to_encounter\n    procedure = get_v2(v2.Procedure,procedure_guid,\\"title\\")\n\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}, {\"line_number\": 147, \"level_number\": 40, \"delta\": \"0.007s\", \"timestamp\": 1446192428.01, \"level_name\": \"ERROR\", \"function_name\": \"create\", \"message\": \"  File \\"\/opt\/sana\/sana.mds\/mds\/api\/v1\/v2compatlib.py\\", line 295, in get_v2\n    obj = klazz.objects.get(**{ field : v })\n\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}, {\"line_number\": 147, \"level_number\": 40, \"delta\": \"0.007s\", \"timestamp\": 1446192428.01, \"level_name\": \"ERROR\", \"function_name\": \"create\", \"message\": \"  File \\"\/usr\/local\/lib\/python2.7\/dist-packages\/django\/db\/models\/manager.py\\", line 151, in get\n    return self.get_queryset().get(_args, *_kwargs)\n\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}, {\"line_number\": 147, \"level_number\": 40, \"delta\": \"0.007s\", \"timestamp\": 1446192428.01, \"level_name\": \"ERROR\", \"function_name\": \"create\", \"message\": \"  File \\"\/usr\/local\/lib\/python2.7\/dist-packages\/django\/db\/models\/query.py\\", line 307, in get\n    self.model._meta.object_name)\n\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}]", 
        "modified": "2015-10-30T03:07:08", 
        "client": "154.122.34.49", 
        "duration": 0.00825905799865723, 
        "path": "/mds/json/procedure/submit/", 
        "requestlog_ptr": {
            "uuid": "fe07c76f-1789-4628-851a-7129a0ed73ed", 
            "level": 16, 
            "created": "2015-10-30T03:07:08", 
            "messages": "[{\"line_number\": 93, \"level_number\": 20, \"delta\": \"0.000s\", \"timestamp\": 1446192428.01, \"level_name\": \"INFO\", \"function_name\": \"create\", \"message\": \"Received saved procedure submission.\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}, {\"line_number\": 96, \"level_number\": 10, \"delta\": \"0.000s\", \"timestamp\": 1446192428.01, \"level_name\": \"DEBUG\", \"function_name\": \"create\", \"message\": \"Data: {'username': u'johndoe', 'procedure_guid': u'API Test', 'responses': u'{}', 'phone': u'9999999999', 'password': u'john123D', 'savedproc_guid': u'14d27ee3-1676-408d-a4c2-c6cedc0dd1af', 'subject': u'7ac6f734-be5a-4b2c-b211-ff523a87bc02'}\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}, {\"line_number\": 79, \"level_number\": 10, \"delta\": \"0.007s\", \"timestamp\": 1446192428.01, \"level_name\": \"DEBUG\", \"function_name\": \"execute\", \"message\": \"(0.000) SELECT `core_procedure`.`id`, `core_procedure`.`uuid`, `core_procedure`.`created`, `core_procedure`.`modified`, `core_procedure`.`title`, `core_procedure`.`author`, `core_procedure`.`description`, `core_procedure`.`version`, `core_procedure`.`src`, `core_procedure`.`voided` FROM `core_procedure` WHERE `core_procedure`.`title` = 'API Test' ; args=(u'API Test',)\", \"module\": \"util\", \"filename\": \"util.py\"}, {\"line_number\": 147, \"level_number\": 40, \"delta\": \"0.007s\", \"timestamp\": 1446192428.01, \"level_name\": \"ERROR\", \"function_name\": \"create\", \"message\": \"  File \\"\/opt\/sana\/sana.mds\/mds\/mrs\/handlers.py\\", line 101, in create\n    encounter, data, created = spform_to_encounter(form.cleaned_data)\n\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}, {\"line_number\": 147, \"level_number\": 40, \"delta\": \"0.007s\", \"timestamp\": 1446192428.01, \"level_name\": \"ERROR\", \"function_name\": \"create\", \"message\": \"  File \\"\/opt\/sana\/sana.mds\/mds\/api\/v1\/v2compatlib.py\\", line 323, in spform_to_encounter\n    procedure = get_v2(v2.Procedure,procedure_guid,\\"title\\")\n\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}, {\"line_number\": 147, \"level_number\": 40, \"delta\": \"0.007s\", \"timestamp\": 1446192428.01, \"level_name\": \"ERROR\", \"function_name\": \"create\", \"message\": \"  File \\"\/opt\/sana\/sana.mds\/mds\/api\/v1\/v2compatlib.py\\", line 295, in get_v2\n    obj = klazz.objects.get(**{ field : v })\n\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}, {\"line_number\": 147, \"level_number\": 40, \"delta\": \"0.007s\", \"timestamp\": 1446192428.01, \"level_name\": \"ERROR\", \"function_name\": \"create\", \"message\": \"  File \\"\/usr\/local\/lib\/python2.7\/dist-packages\/django\/db\/models\/manager.py\\", line 151, in get\n    return self.get_queryset().get(_args, *_kwargs)\n\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}, {\"line_number\": 147, \"level_number\": 40, \"delta\": \"0.007s\", \"timestamp\": 1446192428.01, \"level_name\": \"ERROR\", \"function_name\": \"create\", \"message\": \"  File \\"\/usr\/local\/lib\/python2.7\/dist-packages\/django\/db\/models\/query.py\\", line 307, in get\n    self.model._meta.object_name)\n\", \"module\": \"handlers\", \"filename\": \"handlers.py\"}]", 
            "modified": "2015-10-30T03:07:08", 
            "client": "154.122.34.49", 
            "duration": 0.00825905799865723, 
            "path": "/mds/json/procedure/submit/", 
            "name": "sana-json-procedure-submit"
        }, 
        "name": "sana-json-procedure-submit"
    }
]

**Comment by ewinkler** [comment]
If you load the fixtures in the source, sana.mds/include/mds/fixtures/ directory. 
manage.py loaddata <path-to-fixtures> <filename>.json
That will create the stub procedure for the 'API Test' procedure. For any additional procedures you define, you can add them through the mds admin, /mds/admin/. It is a less than optimal solution at the moment but will become more streamlined when the protocol builder is completed and we no longer rely on the compiled in procedures.

**Comment by endangurura** [comment]
Thanks, I manage to upload successfully. But I have one last issue, what's the currently supported version of OpenMRS, is this http://sana.mit.edu/wiki/index.php?title=OpenMRS_Configuration outdated? Because I can't view the encounter queue in openmrs.

**Comment by ewinkler** [comment]
The supported version is [OpenMRS 1.9.7](http://sourceforge.net/projects/openmrs/files/releases/OpenMRS_1.9.7/openmrs.war/download).

**Comment by endangurura** [comment]
Now I can view the encounter queue but I'm having a problem with the diagnosis and sending SMS notification. I filled in my clickatell information but still no sms notification is being delivered, can you help me to figure out what's going wrong here. Thanks.

# mds logs

[{"line_number": 911, "level_number": 20, "delta": "0.000s", "timestamp": 1447479829.65, "level_name": "INFO", "function_name": "notification_submit", "message": "Notification submit received", "module": "json", "filename": "json.py"}, {"line_number": 914, "level_number": 20, "delta": "0.001s", "timestamp": 1447479829.65, "level_name": "INFO", "function_name": "notification_submit", "message": "Notification submit notificationText:DX: ; Plan: test, test", "module": "json", "filename": "json.py"}, {"line_number": 914, "level_number": 20, "delta": "0.001s", "timestamp": 1447479829.65, "level_name": "INFO", "function_name": "notification_submit", "message": "Notification submit phoneIdentifier:", "module": "json", "filename": "json.py"}, {"line_number": 914, "level_number": 20, "delta": "0.001s", "timestamp": 1447479829.65, "level_name": "INFO", "function_name": "notification_submit", "message": "Notification submit caseIdentifier:SPPQHhsBlcXJukqIyiNGuK", "module": "json", "filename": "json.py"}, {"line_number": 914, "level_number": 20, "delta": "0.002s", "timestamp": 1447479829.65, "level_name": "INFO", "function_name": "notification_submit", "message": "Notification submit patientIdentifier:635872", "module": "json", "filename": "json.py"}]

# Tomcat logs

INFO - LoggingAdvice.invoke(117) |2015-11-14 00:42:47,480| In method EncounterService.saveEncounter. Arguments: Encounter=Encounter: [(no ID) Sat Nov 14 00:42:47 EST 2015 ADULTINITIAL Unknown Location 5 Skin num Obs: [] num Orders: 0 ], 
INFO - LoggingAdvice.invoke(154) |2015-11-14 00:42:47,487| Exiting method saveEncounter
INFO - LoggingAdvice.invoke(117) |2015-11-14 00:42:47,508| In method ObsService.saveObs. Arguments: Obs=obs id is null, String=, 
INFO - LoggingAdvice.invoke(154) |2015-11-14 00:42:47,511| Exiting method saveObs
INFO - LoggingAdvice.invoke(117) |2015-11-14 00:42:47,522| In method ObsService.saveObs. Arguments: Obs=obs id is null, String=, 
INFO - LoggingAdvice.invoke(154) |2015-11-14 00:42:48,069| Exiting method saveObs
INFO - LoggingAdvice.invoke(117) |2015-11-14 00:42:48,084| In method ObsService.saveObs. Arguments: Obs=obs id is null, String=, 
INFO - LoggingAdvice.invoke(154) |2015-11-14 00:42:48,095| Exiting method saveObs
WARN - QueueController.onRequest(78) |2015-11-14 00:43:22,740| In Method: onRequest()
WARN - QueueController.onRequestInternal(124) |2015-11-14 00:43:22,745| ...Queue statusNew
WARN - HibernateQueueItemDAO.getProDateRowsCount(261) |2015-11-14 00:43:22,765| ## Size of QueueItem :7
WARN - HibernateQueueItemDAO.getProDateRowsCount(261) |2015-11-14 00:43:22,775| ## Size of QueueItem :7
WARN - QueueController.onRequest(78) |2015-11-14 00:43:26,948| In Method: onRequest()
WARN - QueueController.onRequestInternal(124) |2015-11-14 00:43:26,957| ...Queue statusNew
WARN - HibernateQueueItemDAO.getProDateRowsCount(261) |2015-11-14 00:43:26,969| ## Size of QueueItem :7
WARN - HibernateQueueItemDAO.getProDateRowsCount(261) |2015-11-14 00:43:26,978| ## Size of QueueItem :7
ERROR - SaveResponseServlet.doPost(156) |2015-11-14 00:43:49,367| Diagnosis 
INFO - LoggingAdvice.invoke(117) |2015-11-14 00:43:49,383| In method ObsService.saveObs. Arguments: Obs=obs id is null, String=, 
INFO - LoggingAdvice.invoke(154) |2015-11-14 00:43:49,385| Exiting method saveObs
INFO - LoggingAdvice.invoke(117) |2015-11-14 00:43:49,411| In method ObsService.saveObs. Arguments: Obs=obs id is null, String=, 
INFO - LoggingAdvice.invoke(154) |2015-11-14 00:43:49,414| Exiting method saveObs
INFO - LoggingAdvice.invoke(117) |2015-11-14 00:43:49,429| In method ObsService.saveObs. Arguments: Obs=obs id is null, String=, 
INFO - LoggingAdvice.invoke(154) |2015-11-14 00:43:49,431| Exiting method saveObs
ERROR - EncounterSaveHandler.handle(51) |2015-11-14 00:43:49,440| Unable to save complex obs
java.lang.NullPointerException
    at org.openmrs.module.sana.queue.handler.ThumbnailingImageHandler.saveObs(ThumbnailingImageHandler.java:167)
    at org.openmrs.api.handler.EncounterSaveHandler.handle(EncounterSaveHandler.java:46)
    at org.openmrs.api.handler.EncounterSaveHandler.handle(EncounterSaveHandler.java:29)
    at org.openmrs.aop.RequiredDataAdvice.recursivelyHandle(RequiredDataAdvice.java:268)
    at org.openmrs.aop.RequiredDataAdvice.recursivelyHandle(RequiredDataAdvice.java:232)
    at org.openmrs.aop.RequiredDataAdvice.before(RequiredDataAdvice.java:138)
    at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:49)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:50)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
    at com.sun.proxy.$Proxy100.saveEncounter(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor634.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:622)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:309)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
    at com.sun.proxy.$Proxy100.saveEncounter(Unknown Source)
    at org.openmrs.module.sana.queue.web.v1.servlet.SaveResponseServlet.doPost(SaveResponseServlet.java:271)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.openmrs.module.web.ModuleServlet.service(ModuleServlet.java:72)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.openmrs.module.web.filter.ForcePasswordChangeFilter.doFilter(ForcePasswordChangeFilter.java:65)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.openmrs.module.web.filter.ModuleFilterChain.doFilter(ModuleFilterChain.java:76)
    at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:83)
    at org.openmrs.module.logmanager.web.filter.RequestProviderFilter.doFilterInternal(RequestProviderFilter.java:36)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
    at org.openmrs.module.web.filter.ModuleFilterChain.doFilter(ModuleFilterChain.java:74)
    at org.openmrs.module.web.filter.ModuleFilter.doFilter(ModuleFilter.java:58)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.openmrs.web.filter.OpenmrsFilter.doFilterInternal(OpenmrsFilter.java:111)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.orm.hibernate3.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:198)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.openmrs.web.filter.StartupFilter.doFilter(StartupFilter.java:109)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.openmrs.web.filter.StartupFilter.doFilter(StartupFilter.java:109)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.openmrs.web.filter.StartupFilter.doFilter(StartupFilter.java:109)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
    at java.lang.Thread.run(Thread.java:701)
INFO - LoggingAdvice.invoke(117) |2015-11-14 00:43:49,449| In method EncounterService.saveEncounter. Arguments: Encounter=Encounter: [20 2015-11-14 00:42:47.0 ADULTINITIAL Unknown Location 5 Skin num Obs: [Obs #103, Obs #102, Obs #104, Obs #101, Obs #100, Obs #99] num Orders: 0 ], 
INFO - LoggingAdvice.invoke(154) |2015-11-14 00:43:49,454| Exiting method saveEncounter
WARN - QueueController.onRequest(78) |2015-11-14 00:43:49,929| In Method: onRequest()
WARN - QueueController.onRequestInternal(124) |2015-11-14 00:43:49,934| ...Queue statusNew
WARN - HibernateQueueItemDAO.getProDateRowsCount(261) |2015-11-14 00:43:49,945| ## Size of QueueItem :6
WARN - HibernateQueueItemDAO.getProDateRowsCount(261) |2015-11-14 00:43:49,954| ## Size of QueueItem :6

**Comment by ewinkler** [comment]
I was able to reproduce the issue but will need to do a bit more work to isolate the root cause. Seems to be an issue with null complex data getting returned for an observation.

**Comment by endangurura** [comment]
Hi Eric,

have you manage to solve the issue.
